version: "3"

x-service-templates:
  api: &api
    image: bhm871/rinha-backend.api:2025
    build:
      dockerfile: src/api/Dockerfile
      additional_contexts:
        - project=.
        - modules=src/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - backend

services:
  nginx:
    image: nginx:1.28.0-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api01
      - api02

  api01:
    <<: *api
    container_name: api01

  api02:
    <<: *api
    container_name: api02

  redis:
    image: redis:8-alpine
    container_name: redis
    networks:
      - backend

  worker:
    image: bhm871/rinha-backend.worker:2025
    build:
      dockerfile: src/worker/Dockerfile
      additional_contexts:
        - project=.
        - modules=src/
    container_name: worker
    environment:
      - PAYMENT_POOL_SIZE=5
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - backend
      - payment-processor

networks:
  backend:
    name: rinha-backend
    driver: bridge
  payment-processor:
    name: payment-processor
    external: true
