version: "3"

x-service-templates:
  api: &api
    image: bhm871/rinha-backend.api:2025
    build:
      dockerfile: src/api/Dockerfile
      additional_contexts:
        - project=.
        - modules=src/
    environment:
      - REDIS_PORT=6379
    networks:
      - backend

services:
  nginx:
    image: nginx:1.28.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - api01

  api01:
    <<: *api
    container_name: api01
    depends_on:
      - redis

  api02:
    <<: *api
    container_name: api02
    depends_on:
      - redis

  redis:
    image: redis:8-alpine
    container_name: redis
    hostname: redis
    networks:
      - backend

networks:
  backend:
    driver: bridge