worker:
    injectors:
        - com.example.worker.app.config.InjectorKt.inject

    processors:
        cache:
            name: "QueueConsumer"
            amount: 1
            module: com.example.worker.processors.CacheProcessor
            batch: ${CONSUMER_BATCH_SIZE:32}
        health:
            name: "PaymentProcessorHealth"
            amount: 1
            module: com.example.worker.processors.HealthProcessor
        payment:
            name: "PaymentProcessor"
            amount: ${PAYMENT_POOL_SIZE:10}
            module: com.example.worker.processors.PaymentProcessor

gateway:
    default:
        host: ${DEFAULT_PAYMENT_HOST:localhost}
        port: ${DEFAULT_PAYMENT_PORT:8001}
    fallback:
        host: ${FALLBACK_PAYMENT_HOST:localhost}
        port: ${FALLBACK_PAYMENT_PORT:8002}

redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    poolSize: ${REDIS_POOL_SIZE:128}