worker:
    injectors:
        - com.example.worker.app.config.InjectorKt.inject

    processors:
        payment:
            name: "PaymentProcessor"
            amount: ${PAYMENT_POOL_SIZE:10}
            module: com.example.worker.processors.PaymentProcessor
        health:
            name: "PaymentProcessorHealth"
            amount: 1
            module: com.example.worker.processors.HealthProcessor

gateway:
    default:
        host: payment-processor-default
        port: 8080
    fallback:
        host: payment-processor-fallback
        port: 8080

redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    poolSize: ${REDIS_POOL_SIZE:128}